parameters:
#    agence_front.example.class: Agence\Bundle\FrontBundle\Example

services:
#    agence_front.example:
#        class: %agence_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
